default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PG_HOST', '127.0.0.1') %>
  username: <%= ENV.fetch('PG_USERNAME', 'postgres') %>
  password: <%= ENV['PG_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  port: <%= ENV.fetch('PG_PORT', 5432) %>

development:
  <<: *default
  database: organiza_feature_development

test:
  <<: *default
  database: organiza_feature_test

production:
  primary: &primary_production
    <<: *default
    database: organiza_feature_production
    username: organiza_feature
    password: <%= ENV["ORGANIZA_FEATURE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: organiza_feature_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: organiza_feature_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: organiza_feature_production_cable
    migrations_paths: db/cable_migrate
